auto delete leftover release branches

diff --git a/.github/workflows/package_release.yml b/.github/workflows/package_release.yml
--- a/.github/workflows/package_release.yml
+++ b/.github/workflows/package_release.yml
@@ -72,10 +72,7 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  # Try to sync the dev branch so it is up to date with the master
-  # if it fails, it fails - no problem (we can still sync manually)
-  sync_dev:
-    if: github.event.pull_request.head.ref == 'dev'
+  housekeeping:
     runs-on: ubuntu-latest
     needs: [package_and_release]
     continue-on-error: true
@@ -87,6 +84,28 @@ jobs:
       - run: |
           git config --local user.name "Handles-Your-Releases"
           git config --local user.email "handles@furcat"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      # Trying to sync the dev branch so it is up to date with the master
+      # if it fails, it fails - no problem (we can still sync manually)
+      - name: Sync Dev
+        run: |
           git fetch origin
           git merge --ff-only master
           git push origin dev
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      # Trying to delete the leftover release branch (eg. release/1.2.3)
+      # We use release tags to navigate the repo at a specific points in time
+      # We can still clean up manually if that doesn't work
+      - name: Delete Leftover Branch
+        run: |
+          if [[ "$BRANCH" == release/* ]]; then
+            git branch -d "$BRANCH" || true
+            git push origin --delete "$BRANCH"
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BRANCH: ${{ github.event.pull_request.head.ref }}
